/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ui.panels;

import glbank.Account;
import glbank.database.ConnectionProvider;
import java.util.List;
import java.util.Random;
import javax.swing.JOptionPane;

/**
 *
 * @author client
 */
public class PanelAccounts extends javax.swing.JPanel {
    private int idc;
    private int idemp;
    
    private List<Account> list;
    /**
     * Creates new form PanelAccounts
     */
    public PanelAccounts(int idc, int idemp) {
        initComponents();
        this.idc=idc;
        this.idemp=idemp;
        initAccountList();
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jAccountList = new javax.swing.JComboBox<>();
        jLabel2 = new javax.swing.JLabel();
        lblBalance = new javax.swing.JLabel();
        jtxtAddValue = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jtxtSubValue = new javax.swing.JTextField();
        jButton2 = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        btnNewAccount = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jtxtAddValue1 = new javax.swing.JTextField();
        jtxtAddValue2 = new javax.swing.JTextField();

        jLabel1.setFont(new java.awt.Font("Algerian", 0, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(51, 153, 0));
        jLabel1.setText("Account id:");

        jAccountList.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jAccountList.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jAccountListActionPerformed(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Algerian", 0, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(51, 204, 0));
        jLabel2.setText("Balance:");

        lblBalance.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        lblBalance.setText("1234.56");

        jtxtAddValue.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jtxtAddValue.setText("0");

        jButton1.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jButton1.setForeground(new java.awt.Color(0, 51, 204));
        jButton1.setText("Add+");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jtxtSubValue.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jtxtSubValue.setText("0");

        jButton2.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jButton2.setForeground(new java.awt.Color(51, 51, 255));
        jButton2.setText("sub -");

        jLabel4.setFont(new java.awt.Font("Algerian", 0, 18)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 204, 0));
        jLabel4.setText("Transaction Cash:");

        btnNewAccount.setFont(new java.awt.Font("Algerian", 0, 18)); // NOI18N
        btnNewAccount.setForeground(new java.awt.Color(255, 0, 0));
        btnNewAccount.setText("Add new account");
        btnNewAccount.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNewAccountActionPerformed(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("Algerian", 0, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 0, 0));
        jLabel3.setText("add New Card");

        jButton3.setForeground(new java.awt.Color(51, 51, 255));
        jButton3.setText("add +");

        jButton4.setForeground(new java.awt.Color(102, 102, 255));
        jButton4.setText("Sub -");

        jtxtAddValue1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jtxtAddValue1.setText("0");

        jtxtAddValue2.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jtxtAddValue2.setText("0");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1)
                            .addComponent(jLabel2)
                            .addComponent(lblBalance)))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jAccountList, javax.swing.GroupLayout.PREFERRED_SIZE, 182, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(29, 29, 29)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel4)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jtxtAddValue, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(18, 18, 18)
                                        .addComponent(jtxtSubValue, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(18, 18, 18)
                                        .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGap(29, 29, 29)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jtxtAddValue1, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jButton3))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jButton4)
                                    .addComponent(jtxtAddValue2, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(btnNewAccount)
                                .addGap(33, 33, 33)
                                .addComponent(jLabel3)))))
                .addContainerGap(337, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jAccountList, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel4))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel2)
                            .addComponent(jtxtAddValue, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jtxtSubValue, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jtxtAddValue1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jtxtAddValue2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblBalance)
                            .addComponent(jButton1)
                            .addComponent(jButton2)
                            .addComponent(jButton3)
                            .addComponent(jButton4)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(7, 7, 7)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btnNewAccount)
                            .addComponent(jLabel3))))
                .addContainerGap(209, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void jAccountListActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jAccountListActionPerformed
        // TODO add your handling code here:
        if(!list.isEmpty()){
            int index=jAccountList.getSelectedIndex();
            lblBalance.setText(""+list.get(index).getBalance());
        }
    }//GEN-LAST:event_jAccountListActionPerformed

    private void btnNewAccountActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNewAccountActionPerformed
        // TODO add your handling code here:
        ConnectionProvider conn=new ConnectionProvider();
        long proposalAccount;
        do{
                 proposalAccount=Math.abs(new Random().nextLong()%900000000)*11;
        }while(conn.existsAccount(proposalAccount));
           System.out.println("New account id: "+proposalAccount);
           conn.insertNewAccount(idc,proposalAccount);
    }//GEN-LAST:event_btnNewAccountActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        String text = jtxtAddValue.getText();
        float value= parseStringToFloat(text);
        value = (float) Math.round(value * 100) / 100;
        System.out.println("value: "+value);
        if(value>=0.1){
            JOptionPane.showMessageDialog(this, "Payment ok.");
            int index=jAccountList.getSelectedIndex();
            long idacc=list.get(index).getIdacc();
            new ConnectionProvider().insertCash(idacc,value,idemp); 
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    private float parseStringToFloat(String text){
        if(text.length()>0){
            try {
                float value=Float.parseFloat(text);
                return value;
            }catch(NumberFormatException ex){
                
            }
        }
        return 0;
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnNewAccount;
    private javax.swing.JComboBox<String> jAccountList;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JTextField jtxtAddValue;
    private javax.swing.JTextField jtxtAddValue1;
    private javax.swing.JTextField jtxtAddValue2;
    private javax.swing.JTextField jtxtSubValue;
    private javax.swing.JLabel lblBalance;
    // End of variables declaration//GEN-END:variables

    private void initAccountList() {
        ConnectionProvider conn = new ConnectionProvider();
        list=conn.getAccounts(idc);
        lblBalance.setText("");
        if(list.isEmpty())
            return;
        
        list.stream().forEach((account) -> {
            jAccountList.addItem(""+account.getIdacc()+" / 2701");
        });
        int index=jAccountList.getSelectedIndex();
        lblBalance.setText(""+list.get(index).getBalance());
    }
}
